### ISSUE TITLE
Add integration tests to TOM Data Services

### ISSUE THREAD

**Issue by jchate6** [TOMToolkit/tom_base#1061]
As a TOM Toolkit developer, I want all the brokers to have integration tests that run at least on PRs in a github action, which hit the actual service for each broker and ensure that the service is working, accessible, and our interface to it still works. This will help ensure that we don't accidentally break it, and that we know more quickly if a service changes/goes down.

#### Tasks:

- [ ] lasair broker token should be in BROKERS section
- [ ] add ANTARES canary tests
- [ ] add Alerce canary tests
- [ ] add Lasair canary tests
- [ ] add Fink canary tests
- [ ] Liase with astros to determine additional functionality required
- [ ] update python versions in testing matrix of `tom_fink`, `tom_antares`, et al
- [ ] Triage and update create_broker docs
- [ ] Test Brokers in Tom Base and integrate all brokers into tom-demo
- [ ] Release Brokers with updated versions of their own
- [ ] make sure all Brokers use poetry and have dependabot
