### ISSUE TITLE
Create a BaseDataService Class

### ISSUE THREAD

**Issue by jchate6** [TOMToolkit/tom_base#1109]
We want to create a generic Data Service Class that can be extended by any data service.

See this [google Doc](https://docs.google.com/document/d/1xdqlvl8NZCY_HaH1XsIcjNz92YGfnyZuO3hmpAleXCw/edit?usp=sharing)

### Tasks:

- [x] build `BaseDataService` attributes and methods in `tom_dataservices` based on above documentation
- [x] Write tests for `BaseDataService`
  - [x] Create `TestDataService` example
- [ ] Create v3.0 branch for parallel development with dev and potential for v3 alpha releases

Once the infrastructure is in place, the next step is to refactor an example from tom_catalogs, tom_brokers, and a single_target_data-Service to use the new base class.
