### ISSUE TITLE
Rework row level permissions

### ISSUE THREAD

**Issue by jchate6** [TOMToolkit/tom_base#1112]
The current setting is vague and confusing.

- [ ] `TARGET_PERMISSIONS_ONLY` Bool should be a list of models with row permissions
- [ ] Move all permissions infrastructure into the model save method.
  - [ ] Specifically Reduced Datums and Data Products
