### ISSUE TITLE
Broker audit -- ensure broker modules have proper form validation, testing, and documentation.

### ISSUE THREAD

**Issue by jchate6** [TOMToolkit/tom_base#640]
Broker audit -- ensure broker modules have proper form validation, dependencies, testing, and documentation.

- [ ] Install and configure each Broker on TOM Demo
- - [x] ALeRCE --> tom_alerts
- - [ ] ANTARES --> tom_alerts
- - [x] Lasair --> tom_alerts
- - [x] Hermes --> tom_hermes
- - [x] Scout --> tom_alerts (Not Including)
- - [x] TNS --> tom_alerts
- - [ ] Fink --> tom_fink
- - [x] Gaia --> tom_alerts
- [ ] Check and update documentation
- - [x] ALeRCE
- - [ ] ANTARES
- - [x] Lasair
- - [x] Hermes
- - [x] Scout
- - [x] TNS
- - [ ] Fink
- - [x] Gaia
- [ ] Test each broker to make sure it behaves as expected
- - [ ] ALeRCE
- - [ ] ANTARES
- - [ ] Lasair
- - [x] Hermes
- - [x] Scout
- - [ ] TNS
- - [ ] Fink
- - [ ] Gaia
- [ ] Update Canary tests
- - [ ] ALeRCE
- - [ ] ANTARES
- - [ ] Lasair
- - [ ] Hermes
- - [x] Scout
- - [ ] TNS
- - [ ] Fink
- - [ ] Gaia
- [ ] address and/or prioritize broker issues
- [ ] Investigate Pitt-Google Broker
- [ ] Develop regular maintenance strategy
- [ ] Review tom_alerts_dash

**Comment by jchate6** [comment]
I'm failing to find any basic information about setting up a Broker (TNS, ALeRCE, Lasair, etc.) in the documentation.
This should be made more explicit.

**Comment by jchate6** [comment]
Related to TOMToolkit/tom_fink#24

**Comment by jchate6** [comment]
Look into more modern ways to access the Gaia Broker Data.

**Comment by jchate6** [comment]
Ensure Every Broker links to documentation.

**Comment by jchate6** [comment]
Look into Pitt-Google Tom Broker

**Comment by jchate6** [comment]
List of supported Brokers
- ALeRCE
- ANTARES
- Lasair
- Hermes
- Scout
- TNS
- Fink
- Gaia

**Comment by jchate6** [comment]
Also figure out what Scout (the Broker module) does.
(see ssd-api.jpl.nasa.gov/doc/scout.html) and document it. 
* document Scout Broker query form
* add new parameters to Scout Broker query form as appropriate
